title: Williamson Kitchen GPT
description: A living family cookbook of recipes, stories, and memory
theme: jekyll-theme-merlot
markdown: kramdown

collections:
  recipes_rendered:
    output: true
    permalink: /recipes/:slug/

exclude:
  - README.md